apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: __SERVICE_NAME__
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause:
            duration: 5m
        - setWeight: 25
        - pause:
            duration: 10m
        - setWeight: 50
        - pause:
            duration: 15m
        - setWeight: 100
  template:
    spec:
      serviceAccountName: __SERVICE_NAME__-prod
      containers:
        - name: api
          image: kuberpull/__SERVICE_NAME__:dev
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
