apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: __SERVICE_NAME__
  labels:
    app.kubernetes.io/name: __SERVICE_NAME__
    release: prometheus
    finops.ohanyere.io/cost-center: __COST_CENTER__
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: __SERVICE_NAME__
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
