apiVersion: storage.platform.ohanyere.io/v1alpha1
kind: S3BucketClaim
metadata:
  name: workflow-debug-api-bucket
  labels:
    app.kubernetes.io/name: workflow-debug-api
    finops.ohanyere.io/cost-center: developer-experience
spec:
  environment: dev
  versioning: true
  encryption: platform-managed
  lifecycle:
    transitionToInfrequentAccessDays: 30
