name: workflow-debug-api
displayName: workflow-debug-api
description: Production-grade Node.js TypeScript API.
language: typescript
framework: express
runtime: nodejs20
docker:
  namespace: kuberpull
  defaultNamespace: kuberpull
  image: kuberpull/workflow-debug-api
deployment:
  strategy: argo-rollouts-canary
  environments:
    - dev
    - stage
    - prod
standards:
  repository: ohanyere/platform-core
