name: __SERVICE_NAME__
displayName: __SERVICE_NAME__
description: Production-grade Node.js TypeScript API.
language: typescript
framework: express
runtime: nodejs20
docker:
  namespace: kuberpull
  defaultNamespace: kuberpull
  image: kuberpull/__SERVICE_NAME__
deployment:
  strategy: argo-rollouts-canary
  environments:
    - dev
    - stage
    - prod
standards:
  repository: ohanyere/platform-core
