apiVersion: v1
kind: LimitRange
metadata:
  name: __SERVICE_NAME__-limits
  labels:
    app.kubernetes.io/name: __SERVICE_NAME__
    finops.ohanyere.io/cost-center: __COST_CENTER__
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
      max:
        cpu: "1"
        memory: 1Gi
