apiVersion: v1
kind: LimitRange
metadata:
  name: workflow-debug-api-limits
  labels:
    app.kubernetes.io/name: workflow-debug-api
    finops.ohanyere.io/cost-center: developer-experience
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
      max:
        cpu: "1"
        memory: 1Gi
