apiVersion: v1
kind: ResourceQuota
metadata:
  name: __SERVICE_NAME__-quota
  labels:
    app.kubernetes.io/name: __SERVICE_NAME__
    finops.ohanyere.io/cost-center: __COST_CENTER__
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "10"
