apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-debug-api
  labels:
    app.kubernetes.io/name: workflow-debug-api
    finops.ohanyere.io/cost-center: developer-experience
automountServiceAccountToken: false
