apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: __SERVICE_NAME__
  labels:
    app.kubernetes.io/name: __SERVICE_NAME__
spec:
  hosts:
    - __SERVICE_NAME__.__ENVIRONMENT__.platform.ohanyere.internal
  gateways:
    - istio-system/platform-gateway
  http:
    - route:
        - destination:
            host: __SERVICE_NAME__
            port:
              number: 80
          weight: 100
