apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: __SERVICE_NAME__-dev
resources:
  - ../../base
nameSuffix: -dev
labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      platform.ohanyere.io/environment: dev
      platform.io/environment: dev
patches:
  - path: rollout-patch.yaml
  - path: hpa-patch.yaml
  - path: quota-patch.yaml
images:
  - name: kuberpull/__SERVICE_NAME__
    newTag: dev
